version: "3"

services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - ./data:/data/db
  app:
    depends_on:
      - db
    build: ./app
    ports:
      - "8080:8080"

volumes:
  db:
